"use client";

import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";
import { computeInvoiceTotals } from "@/lib/invoice";
import type { Business, GeneratedInvoice, InvoiceItem } from "@/lib/types";

const styles = StyleSheet.create({
  page: { padding: 32, fontSize: 11, color: "#0f172a" },
  header: { flexDirection: "row", justifyContent: "space-between", marginBottom: 16 },
  bizName: { fontSize: 18, fontWeight: 700 },
  meta: { fontSize: 9, color: "#64748b" },
  title: { fontSize: 14, fontWeight: 700, marginVertical: 8 },
  row: {
    flexDirection: "row",
    borderBottom: "1pt solid #e2e8f0",
    paddingVertical: 6,
  },
  th: { flex: 1, fontWeight: 700, fontSize: 9, color: "#475569" },
  td: { flex: 1, fontSize: 10 },
  totals: { marginTop: 12, alignSelf: "flex-end", width: 220 },
  totalRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 2 },
  grand: { fontWeight: 700, fontSize: 13 },
  footer: { marginTop: 24, fontSize: 9, color: "#94a3b8", textAlign: "center" },
});

export function InvoicePdf({
  business,
  invoice,
}: {
  business: Business;
  invoice: GeneratedInvoice;
}) {
  const items: InvoiceItem[] = invoice.items;
  const { subtotal, gst, total } = computeInvoiceTotals(items);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View>
            <Text style={styles.bizName}>{business.name}</Text>
            <Text style={styles.meta}>{business.address}</Text>
            <Text style={styles.meta}>GST: {business.gst}</Text>
          </View>
          <View>
            <Text style={styles.meta}>Invoice: {invoice.invoiceId}</Text>
            <Text style={styles.meta}>Date: {invoice.date}</Text>
            <Text style={styles.meta}>Bill to: {invoice.customer}</Text>
          </View>
        </View>

        <Text style={styles.title}>Tax Invoice</Text>

        <View style={styles.row}>
          <Text style={styles.th}>Item</Text>
          <Text style={styles.th}>Qty</Text>
          <Text style={styles.th}>Rate</Text>
          <Text style={styles.th}>Amount</Text>
        </View>
        {items.map((it, idx) => (
          <View style={styles.row} key={idx}>
            <Text style={styles.td}>{it.name}</Text>
            <Text style={styles.td}>{it.quantity}</Text>
            <Text style={styles.td}>₹{it.price}</Text>
            <Text style={styles.td}>₹{it.quantity * it.price}</Text>
          </View>
        ))}

        <View style={styles.totals}>
          <View style={styles.totalRow}>
            <Text>Subtotal</Text>
            <Text>₹{subtotal}</Text>
          </View>
          <View style={styles.totalRow}>
            <Text>GST (18%)</Text>
            <Text>₹{gst}</Text>
          </View>
          <View style={[styles.totalRow, styles.grand]}>
            <Text>Total</Text>
            <Text>₹{total}</Text>
          </View>
          <Text style={styles.meta}>Payment: {invoice.paymentMethod}</Text>
        </View>

        <Text style={styles.footer}>Generated by VyaparAI — AI Employee for Your Business</Text>
      </Page>
    </Document>
  );
}
